services:

  db:
    image: postgres:15-alpine
    container_name: receiptai_db
    environment:
      - POSTGRES_DB=receiptai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: